//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Archtype&gt;
        ///  &lt;shangYe Name=&quot;商业&quot; Code=&quot;shangYe&quot;&gt;
        ///      &lt;Archtypeitem Name=&quot;超市&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;商场&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;餐饮&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;精品店&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;购物街&quot; /&gt;
        ///  &lt;/shangYe&gt;
        ///
        ///  &lt;jiuDian Name=&quot;酒店&quot; Code=&quot;jiuDian&quot;&gt;
        ///    
        ///      &lt;Archtypeitem Name=&quot;商务酒店&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;旅游度假酒店&quot; /&gt;
        ///      &lt;Archtypeitem Name=&quot;会议酒店&quot; /&gt;
        ///    
        ///  &lt;/jiuDian&gt;
        ///
        ///  &lt;banGong Name=&quot;办公&quot; Code=&quot;banGong&quot;&gt;
        ///    
        ///      &lt;Archtyp [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string archType {
            get {
                return ResourceManager.GetString("archType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Location&gt;
        ///  &lt;CountryRegion Name=&quot;中国&quot; Code=&quot;1&quot;&gt;
        ///    &lt;State Name=&quot;北京&quot; Code=&quot;11&quot;&gt;
        ///      &lt;City Name=&quot;东城&quot; Code=&quot;1&quot;/&gt;
        ///      &lt;City Name=&quot;西城&quot; Code=&quot;2&quot;/&gt;
        ///      &lt;City Name=&quot;崇文&quot; Code=&quot;3&quot;/&gt;
        ///      &lt;City Name=&quot;宣武&quot; Code=&quot;4&quot;/&gt;
        ///      &lt;City Name=&quot;朝阳&quot; Code=&quot;5&quot;/&gt;
        ///      &lt;City Name=&quot;丰台&quot; Code=&quot;6&quot;/&gt;
        ///      &lt;City Name=&quot;石景山&quot; Code=&quot;7&quot;/&gt;
        ///      &lt;City Name=&quot;海淀&quot; Code=&quot;8&quot;/&gt;
        ///      &lt;City Name=&quot;门头沟&quot; Code=&quot;9&quot;/&gt;
        ///      &lt;City Name=&quot;房山&quot; Code=&quot;11&quot;/&gt;
        ///      &lt;City Name=&quot;通州&quot; Code=&quot;12&quot;/&gt;
        ///      &lt;City [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1897
        ///1898
        ///1899
        ///1900
        ///1901
        ///1902
        ///1903
        ///1904
        ///1905
        ///1906
        ///1907
        ///1908
        ///1909
        ///1910
        ///1911
        ///1912
        ///1913
        ///1914
        ///1915
        ///1916
        ///1917
        ///1918
        ///1919
        ///1920
        ///1921
        ///1922
        ///1923
        ///1924
        ///1925
        ///1926
        ///1927
        ///1928
        ///1929
        ///1930
        ///1931
        ///1932
        ///1933
        ///1934
        ///1935
        ///1936
        ///1937
        ///1938
        ///1939
        ///1940
        ///1941
        ///1942
        ///1943
        ///1944
        ///1945
        ///1946
        ///1947
        ///1948
        ///1949
        ///1950
        ///1951
        ///1952
        ///1953
        ///1954
        ///1955
        ///1956
        ///1957
        ///1958
        ///1959
        ///1960
        ///1961
        ///1962
        ///1963
        ///1964
        ///1965
        ///1966
        ///1967
        ///1968
        ///1969
        ///1970
        ///1971
        ///1972
        ///1973
        ///1974
        ///1975
        ///1976
        ///1977
        ///1978
        ///1979
        ///1980
        ///1981
        ///19 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string yearList {
            get {
                return ResourceManager.GetString("yearList", resourceCulture);
            }
        }
    }
}
